#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 阻止主分支代码提交
branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" = "main" ]; then
  echo "You can't commit to main!"
  exit 1
fi

echo "git commit trigger husky pre-commit hook" && npx lint-staged
